language: r
cache: packages

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  # No Mac for now
  #- r: release
  #  os: osx

r_github_packages:
  - richelbilderbeek/beautier
  - richelbilderbeek/beastier
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/spelling

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf

before_script:
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi
  # PDF
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr update --self; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install inconsolata; fi
  # Lapack
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then locate lapack.so || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then locate libRlapack.so || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install liblapack-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install r-cran-ade4; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then locate lapack.so || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then locate lapack3.so || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then locate libRlapack.so || true; fi
  # babette must build cleanly without BEAST2 installed, as on CRAN there is no install script
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install proselint; fi

script:
  - travis_wait 30 R CMD build .
  - travis_wait 40 R CMD check *tar.gz

after_success:
  # Lint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then Rscript -e 'lintr::lint_package()'; fi
  # Codecov
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
  # Goodpractice
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then travis_wait 60 Rscript -e 'goodpractice::gp()'; fi
  # Proselint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes" | egrep -v "typography\.symbols\.sentence_spacing" ; fi
  # No local files created
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/check_no_local_files; fi
  # Do a CRAN build. No time :-(
  #- cd scripts; ./build_cran
  # temporarily disabled due to CERT_UNTRUSTED
  #- ./scripts/check_dead_links
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

after_failure:
  - cat /home/travis/build/ropensci/babette/..Rcheck/00install.out
  - cat /home/travis/build/ropensci/babette/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/ropensci/babette/..Rcheck/tests/testthat/testthat.log
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

